/*****Generated by ClientConfigTool!*****/ 
/*****Do Not Edit!*****/

using UnityEngine;
using System.Collections;

namespace Games.GlobeDefine
{
    [SLua.CustomLuaClass]
    public class GameStruct_AutoActivityConfig
    {
        public bool IsConfigEnable = false;
        public string ActivityPriority = "";
        public string StrActivityUnopenTip = "";
        public string StrActivityOverTip = "";
        public string StrActivityErrorTip = "";
        public string StrFunUnopenTip = "";
        public string StrFunErrorTip = "";

		public void LoadFile()
		{
			string content = Utils.ReadIniFile("Config/ActivityConfig");
			Load(content);
		}

        public static string GetFileName() { return "ActivityConfig.txt"; }
        public static string GetFilePath() { return "Config/ActivityConfig.txt"; }

		public bool Load(string content)
		{
			try
            {
				IniFile ini = new IniFile(content);




				IsConfigEnable = ini.read_bool("config","IsConfigEnable",IsConfigEnable);


				ActivityPriority = ini.read_string("config","ActivityPriority",ActivityPriority);
				StrActivityUnopenTip = ini.read_string("config","StrActivityUnopenTip",StrActivityUnopenTip);
				StrActivityOverTip = ini.read_string("config","StrActivityOverTip",StrActivityOverTip);
				StrActivityErrorTip = ini.read_string("config","StrActivityErrorTip",StrActivityErrorTip);
				StrFunUnopenTip = ini.read_string("config","StrFunUnopenTip",StrFunUnopenTip);
				StrFunErrorTip = ini.read_string("config","StrFunErrorTip",StrFunErrorTip);

			}
			catch (System.Exception ex)
			{
				UnityEngine.Debug.LogError("load ini file error." + GetFileName());
				UnityEngine.Debug.LogException(ex);
				return false;
			}
			return true;
		}
    }
}
